### ISSUE TITLE
Which choice should be choosed when static-analyzing the linux kernel?

### ISSUE THREAD

**Issue by dengnan0819** [ucsb-seclab/actor#1]
SYNC    include/config/auto.conf.cmd
*
* Restart config...
*
*
* Memory initialization
*
Initialize kernel stack variables at function entry
> 1. no automatic stack variable initialization (weakest) (INIT_STACK_NONE)
  2. pattern-init everything (strongest) (INIT_STACK_ALL_PATTERN) (NEW)
  3. zero-init everything (strongest and safest) (INIT_STACK_ALL_ZERO) (NEW)
choice[1-3?]: 

Which choice should be choosed when static-analyzing the linux kernel?
Whether different choices affect the analysis results?

**Comment by olmeke** [comment]
Hi,
For the analysis that we perform on the kernel, this config option most likely should not have any effect (we are not concerned with whether or how variables are initialized). More generally speaking, for the optimal result for your setup, I would recommend first crafting the kernel config that you want, then adding the required options for Actor to the config, and using this final result for the static analysis and fuzzing.

Hope this helps! Let me know if you have any other questions.
