### ISSUE TITLE
Hi, how to solve this problem: “panic: runtime error: slice bounds out of range [34:26]”

### ISSUE THREAD

**Issue by dengnan0819** [ucsb-seclab/actor#2]
2023/09/12 03:36:58 result hanged=false: 
[DEBUG] [744767ms] exec opts: procid=0 threaded=1 cover=0 comps=0 event=1 dedup=1 signal=0 timeouts=50/5000/1 prog=0 filter=0
 exec_id=436201798spawned worker pid 31908
[DEBUG]: Thread 0 is being scheduled
[DEBUG]: Worker 0 in action
event enabled pid=31908
#0,31908 [744770ms] -> close(0xffffffffffffffff)
#0,31908 [744770ms] <- close=0xffffffffffffffff errno=9 cover=0event=0 
event stop pid=31908
executor recorded 0 events
[DEBUG]: Thread 0 is being scheduled
panic: runtime error: slice bounds out of range [34:26]

goroutine 910 [running]:
main.(*RPCServer).find_trigg_instruction(0xc00097c700, {0x1, 0x1, 0xffff88800c766700, 0xa8, 0x9, 0x0, 0x0, 0x0, {0xc001fcfac0, ...}, ...})
	/home/workdir/actor/gopath/src/github.com/google/syzkaller/syz-manager/evtrack.go:618 +0x753
main.(*RPCServer).group_events(0xc00097c700, {0xc000981800, 0x5e, 0xc0020bf6e8?})
	/home/workdir/actor/gopath/src/github.com/google/syzkaller/syz-manager/evtrack.go:445 +0x5a5
main.(*RPCServer).add_groups(0xc00097c700, {0xc000981800?, 0x0?, 0x17b63a8?})
	/home/workdir/actor/gopath/src/github.com/google/syzkaller/syz-manager/evtrack.go:298 +0x3e
created by main.(*RPCServer).PollNew
	/home/workdir/actor/gopath/src/github.com/google/syzkaller/syz-manager/rpc.go:488 +0x1b0f

**Comment by olmeke** [comment]
Hi,
How long after starting the fuzzing run does it take for this crash to come up?
Can you please try the following and post the output here?
before /home/workdir/actor/gopath/src/github.com/google/syzkaller/syz-manager/evtrack.go:618 insert the following line:
`log.Logf(0, "addr2line output %v || kerneldir %v\n", out_s, serv.unpackedCfg["kernelDir"])`

There can be an issue with this if addr2line is not able to resolve the address properly, but in that case, the crash would look slightly different.

**Comment by dengnan0819** [comment]
Personal error, thanks for your reply.
