### ISSUE TITLE
Errors after run "make CC=../semantic-inference/my-clang -j$(nproc) 2>ptrs.txt"

### ISSUE THREAD

**Issue by MuseMamba** [ucsb-seclab/actor#3]
Hi, you have done an excellent job. 
However, I encountered a problem during deployment and would like to seek your advice on it.

When I follow the steps and finished "make CC=../semantic-inference/my-clang -j$(nproc) 2>ptrs.txt", in ptrs.txt, it got errors:

Errors:----------------------------------------------------------------------------------------------
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.6 (git@github.com:llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ls/llvm14/llvm-project/build/bin
clang-14: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/devio-cae183.c
clang-14: note: diagnostic msg: /tmp/devio-cae183.sh
clang-14: note: diagnostic msg:

********************
make[4]: *** [scripts/Makefile.build:252：drivers/usb/core/devio.o] error 134
make[3]: *** [scripts/Makefile.build:504：drivers/usb/core] error 2
make[2]: *** [scripts/Makefile.build:504：drivers/usb] error 2
make[1]: *** [scripts/Makefile.build:504：drivers] error 2
Killed
make[2]: *** [scripts/Makefile.build:252：arch/x86/power/cpu.o] error 137
make[1]: *** [scripts/Makefile.build:504：arch/x86/power] error 2
make: *** [Makefile:2021：.] error 2
Error end.------------------------------------------------------------------------------------------------

I used "makedefconfig" to get the config file.
The kernel version is 2241ab53cbb5, as the "README" said.
My OS is ：
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

I am very grateful for any tips you can give me.

Thanks a lot.

**Comment by olmeke** [comment]
Hi,
let me try and reproduce it, I think I only ever used in on 20.04. Given that you used `make defconfig ` I assume you are not trying to cross-compile to a different arch, right?

**Comment by MuseMamba** [comment]
Thank you for your reply. Yes, I am not trying to cross-compile to a different arch. And based on defconfig, I also used the command"./scripts/kconfig/merge_config.sh .config ../setup/kernel/actor_static.config".

**Comment by olmeke** [comment]
I dockerized the static analysis part. Please try it out and let me know if it works for you. Instructions are in the readme

**Comment by MuseMamba** [comment]
It running smoothly! I appreciate your help! By the way, I like your job, the engineering implementation is beautiful! Looking forward to your new work!

**Comment by olmeke** [comment]
Awesome! Thanks :)
