### ISSUE TITLE
Is it normal that actor will generate lots of SYZFATAL?

### ISSUE THREAD

**Issue by 1ncande5cence** [ucsb-seclab/actor#7]
Hi, I ran actor on kernel version v6.2rc-5 with all the settings the repo provides. After running for 7 hours, it generated over 100+ SYZFATAL and the vm restarts number is 411 (57/hour). It got even worse when I provided a large corpus. What could be the possible reasons for that?

Thank you for your time!

**Comment by 1ncande5cence** [comment]
I'm using `.config` generated by syzbots

**Comment by olmeke** [comment]
For future reference, @1ncande5cence and I nailed down the issue to the corpus they were using. A very large corpus leads to the VMs constantly running OOM. Running on a smaller/no corpus leads to normal behavior
